---
title: "Mortality from COVID"
author: "Danny Wong"
date: "19/03/2020"
output:
  word_document:
    reference_docx: styles_phd.docx
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(lubridate)
library(scales)
library(broom)
library(pander)
panderOptions('table.split.table', Inf)

population <- read.csv("../data/population.csv", skip = 4, stringsAsFactors = FALSE) %>%
  rename(Country.Region = Country.Name) %>%
  mutate(Country.Region = recode(Country.Region, `Bahamas, The` = "Bahamas",
                                 `Brunei Darussalam` = "Brunei",
                                 `Congo, Rep.` = "Congo",
                                 `Congo, Dem. Rep.` = "Democratic Republic of Congo",
                                 `Egypt, Arab Rep.` = "Egypt",
                                 `Eswatini` = "Swaziland",
                                 `Faroe Islands` = "Faeroe Islands",
                                 `Iran, Islamic Rep.` = "Iran",
                                 `North Macedonia` = "Macedonia",
                                 `Korea, Rep.` = "South Korea",
                                 `Russian Federation` = "Russia",
                                 `St. Lucia` = "Saint Lucia",
                                 `St. Martin (French part)` = "Saint Martin (French part)",
                                 `St. Vincent and the Grenadines` = "Saint Vincent and the Grenadines",
                                 `Slovak Republic` = "Slovakia",
                                 `Virgin Islands (U.S.)` = "United States Virgin Islands",
                                 `Venezuela, RB` = "Venezuela")) %>%
  select(Country.Region, popn = X2018)

covid_raw <- read.csv("https://covid.ourworldindata.org/data/ecdc/full_data.csv", stringsAsFactors = FALSE)
covid_data <- covid_raw %>%
  rename(Country.Region = location) %>%
  mutate(date = ymd(date)) %>%
  filter(date <= ymd("2020-03-19")) %>%
  left_join(population, by = "Country.Region") %>%
  mutate(cases_per_capita = total_cases/popn * 100000) %>%
  mutate(deaths_per_capita = total_deaths/popn * 100000)

country <- unique(covid_data$Country.Region)
earliest_date <- min(covid_data$date)
latest_date <- max(covid_data$date)
data_source <- "Data from https://ourworldindata.org/coronavirus-source-data"
```

## Mortality Models from COVID-19

`r print(data_source)`

We would like to see what the mortality might be going forward. We can do a log transformation of the total deaths and regress against the Days since 10 deaths.

```{r echo=FALSE}
#G7 Countries
G7 <- c("France", "Germany", "Italy", "Japan", "United Kingdom", "United States", "Canada")
G7_China <- c(G7, "China")

# Create a subset of the data of the UK similar countries, and then align their dates, 
# such that Day 0 is the first day they reported at least 10 deaths
# Also create a log-transformed variable for deaths and a variable for Days since 10 deaths
# Days will be the relative timing variable
covid_data_subset <- covid_data %>% 
  filter(Country.Region %in% G7_China) %>%
  mutate(log_deaths = log(total_deaths, base = 10)) %>%
  mutate(log_deaths_per_capita = log(deaths_per_capita, base = 10)) %>%
  filter(total_deaths >= 10 & total_cases >= 100) %>%
  group_by(Country.Region) %>% 
  mutate(Days = seq(from = 0, to = n()-1)) %>%
  filter(Days >= 0 & Days <= 21) #Select the first 21 days

# Create a similar subset of cases >= 100.
covid_cases_subset <- covid_data %>% 
  filter(Country.Region %in% G7_China) %>%
  mutate(log_cases = log(total_cases, base = 10)) %>%
  mutate(log_cases_per_capita = log(cases_per_capita, base = 10)) %>%
  filter(total_deaths >= 10 & total_cases >= 100) %>%
  group_by(Country.Region) %>% 
  mutate(Days = seq(from = 0, to = n()-1)) %>%
  filter(Days >= 0 & Days <= 21) #Select the first 21 days

# Fit the models for deaths
fitted_models_deaths <- covid_data_subset %>% 
  group_by(Country.Region) %>% 
  do(model = lm(log_deaths ~ Days, data = .))

fitted_models_deaths_per_capita <- covid_data_subset %>% 
  group_by(Country.Region) %>% 
  do(model = lm(log_deaths_per_capita ~ Days, data = .))

# Fit the models for cases
fitted_models_cases <- covid_cases_subset %>% 
  group_by(Country.Region) %>% 
  do(model = lm(log_cases ~ Days, data = .))

fitted_models_cases_per_capita <- covid_cases_subset %>% 
  group_by(Country.Region) %>% 
  do(model = lm(log_cases_per_capita ~ Days, data = .))

# View the models
fitted_models_deaths %>% tidy(model) %>% pander::pander("Table 1: Coefficients of linear regression models for log(DEATHS) against DAYS since 10 deaths.")
fitted_models_deaths %>% glance(model) %>% pander::pander("Table 2: Fit statistics of linear regression models for log(DEATHS) against DAYS since 10 deaths.")

fitted_models_deaths_per_capita %>% tidy(model) %>% pander::pander("Table 3: Coefficients of linear regression models for log(DEATHS_PER_CAPITA) against Days since 10 deaths.")
fitted_models_deaths_per_capita %>% glance(model) %>% pander::pander("Table 4: Fit statistics of linear regression models for log(DEATHS) against DAYS since 10 deaths.")

fitted_models_cases %>% tidy(model) %>% pander::pander("Table 5: Coefficients of linear regression models for log(CASES) against DAYS since 100 cases.")
fitted_models_cases %>% glance(model) %>% pander::pander("Table 6: Fit statistics of linear regression models for log(CASES) against DAYS since 100 cases.")

fitted_models_deaths_per_capita %>% tidy(model) %>% pander::pander("Table 7: Coefficients of linear regression models for log(CASES_PER_CAPITA) against DAYS since 100 cases.")
fitted_models_deaths_per_capita %>% glance(model) %>% pander::pander("Table 8: Fit statistics of linear regression models for log(CASES) against DAYS since 100 cases.")
```

## Plots

Now we can plot the data and the models.

### Deaths

```{r plot_deaths, echo=FALSE, message=FALSE, warning=FALSE, dpi=300, height=8, width=12}
covid_data_subset %>%
  ggplot(aes(x = Days, y = total_deaths, col = Country.Region)) + 
  geom_point(alpha = 0.8) +
  geom_smooth(method = "lm", fullrange = TRUE, size = 0.5) +
  labs(x = paste("Day number since 10 cumulative deaths"), 
       y = "Deaths",
       title = "Deaths over time",
       col = "Country") +
  scale_y_continuous(trans = "log10", labels = scales::comma_format()) +
  theme_bw() +
  theme(legend.position="bottom") +
  theme(axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 16, face = "bold"))
ggsave("../plots/figure1.pdf", dpi = 300, width = 12, height = 8, device = cairo_pdf)
```

### Deaths Per Capita

```{r plot_deaths_per_capita, echo=FALSE, message=FALSE, warning=FALSE, dpi=300, height=8, width=12}
covid_data_subset %>%
  ggplot(aes(x = Days, y = deaths_per_capita, col = Country.Region)) + 
  geom_point() +
  geom_smooth(method = "lm", fullrange = TRUE, size = 0.5) +
  labs(x = paste("Day number since 10 cumulative deaths"), 
       y = "Deaths per 100,000 population",
       title = "Deaths per capita over time",
       col = "Country",
       linetype = "Country") +
  scale_y_continuous(trans = "log10", labels = scales::comma_format(accuracy = 0.01)) +
  theme_bw() +
  theme(legend.position="bottom") +
  theme(axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 16, face = "bold"))
ggsave("../plots/figure2.pdf", dpi = 300, width = 12, height = 8, device = cairo_pdf)
```

### Cases

```{r plot_cases, echo=FALSE, message=FALSE, warning=FALSE, dpi=300, height=8, width=12}
covid_cases_subset %>%
  ggplot(aes(x = Days, y = total_cases, col = Country.Region)) + 
  geom_point() +
  geom_smooth(method = "lm", fullrange = TRUE, size = 0.5) +
  labs(x = paste("Day number since 100 cumulative cases"), 
       y = "Cases",
       title = "Forecasted cases with date offset",
       col = "Country") +
  scale_y_continuous(trans = "log10", labels = scales::comma_format()) +
  theme_bw() +
  theme(legend.position="bottom") +
  theme(axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 16, face = "bold"))
ggsave("../plots/figure3.pdf", dpi = 300, width = 12, height = 8, device = cairo_pdf)
```

### Cases Per Capita

```{r plot_cases_per_capita, echo=FALSE, message=FALSE, warning=FALSE, dpi=300, height=8, width=12}
covid_cases_subset %>%
  ggplot(aes(x = Days, y = cases_per_capita, col = Country.Region)) + 
  geom_point() +
  geom_smooth(method = "lm", fullrange = TRUE, size = 0.5) +
  labs(x = paste("Day number since 100 cumulative cases"), 
       y = "Cases per 100,000 population",
       title = "Forecasted cases with date offset (log scale)",
       col = "Country",
       linetype = "Country") +
  scale_y_continuous(trans = "log10", labels = scales::comma_format(accuracy = 0.01)) +
  theme_bw() +
  theme(legend.position="bottom") +
  theme(axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 16, face = "bold"))
ggsave("../plots/figure4.pdf", dpi = 300, width = 12, height = 8, device = cairo_pdf)
```

### Deaths per capita UK, Italy and China

```{r plot_deaths_per_capita_China, echo=FALSE, message=FALSE, warning=FALSE, dpi=300, height=8, width=12}
covid_data_subset %>% filter(Country.Region %in% c("Italy", "China", "United Kingdom")) %>%
  ggplot(aes(x = Days, y = deaths_per_capita, col = Country.Region)) + 
  geom_point() +
  geom_smooth(method = "lm", fullrange = TRUE, size = 0.5) +
  labs(x = paste("Day number since 10 cumulative deaths"), 
       y = "Deaths per 100,000 population",
       title = "Deaths per capita over time",
       col = "Country",
       linetype = "Country") +
  scale_y_continuous(trans = "log10", labels = scales::comma_format(accuracy = 0.01)) +
  theme_bw() +
  theme(legend.position="bottom") +
  theme(axis.title.x = element_text(size = 14, face = "bold"),
        axis.title.y = element_text(size = 14, face = "bold"),
        plot.title = element_text(size = 16, face = "bold"))
ggsave("../plots/figure5.pdf", dpi = 300, width = 12, height = 8, device = cairo_pdf)
```

### Result Table

```{r echo=FALSE, message=FALSE, warning=FALSE}
a <- fitted_models_deaths_per_capita %>% 
  tidy(model) %>% 
  filter(term == "Days") %>%
  mutate(lwr = estimate - (1.96 * std.error)) %>%
  mutate(upr = estimate + (1.96 * std.error)) %>%
  mutate(daily_multiplier = 10^estimate) %>%
  mutate(daily_inc_percent = (daily_multiplier - 1) * 100) %>%
  mutate(daily_multiplier_lwr = 10^lwr) %>%
  mutate(daily_inc_percent_lwr = (daily_multiplier_lwr - 1) * 100) %>%
  mutate(daily_multiplier_upr = 10^upr) %>%
  mutate(daily_inc_percent_upr = (daily_multiplier_upr - 1) * 100) %>%
  mutate(ci = paste0(round(daily_inc_percent_lwr, digits = 2), "-", round(daily_inc_percent_upr, digits = 2))) %>%
  select(`Daily increases in Deaths per 100,000 population (%)` = daily_inc_percent,
         `Deaths (95% CI)` = ci)

b <- fitted_models_cases_per_capita %>% 
  tidy(model) %>% 
  filter(term == "Days") %>% 
  mutate(lwr = estimate - (1.96 * std.error)) %>%
  mutate(upr = estimate + (1.96 * std.error)) %>%
  mutate(daily_multiplier = 10^estimate) %>%
  mutate(daily_inc_percent = (daily_multiplier - 1) * 100) %>%
  mutate(daily_multiplier_lwr = 10^lwr) %>%
  mutate(daily_inc_percent_lwr = (daily_multiplier_lwr - 1) * 100) %>%
  mutate(daily_multiplier_upr = 10^upr) %>%
  mutate(daily_inc_percent_upr = (daily_multiplier_upr - 1) * 100) %>%
  mutate(ci = paste0(round(daily_inc_percent_lwr, digits = 2), "-", round(daily_inc_percent_upr, digits = 2))) %>%
  select(`Daily increases in Cases per 100,000 population (%)` = daily_inc_percent,
         `Cases (95% CI)` = ci)

results_table <- left_join(a, b, by = "Country.Region") %>%
  arrange(desc(`Daily increases in Deaths per 100,000 population (%)`))

results_table %>% arrange(desc(`Daily increases in Deaths per 100,000 population (%)`))%>% pander::pander(paste0("Results Table 1: Daily rate of increase of deaths and cases per capita for each country analysed. The United Kingdom shows a daily rate of increase in the number of deaths per 100,000 population of ", (results_table %>% filter(Country.Region == "United Kingdom") %>% pull(`Daily increases in Deaths per 100,000 population (%)`)), "%, based on our model."))
```
